/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TwitterIcons {
  TwitterIcons._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData logo = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData featured = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData homeAlternate = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData message = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData messageAlternate = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData notification = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData notificationAlternate = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData searchAlternate = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData favoriteAlternate = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData favorite = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData comment = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData retweet = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData retweetAlternate = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData verified = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData play = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe812, fontFamily: _kFontFam);
}
